apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../stress-jobs
  - priorityclasses.yaml

patches:
  - path: sentinel-qos-priority-patch.yaml
  - path: stress-low-priority-patch.yaml
