apiVersion: v1
data:
  snmp.conf: |
    jobs:
      - name: openwrt_ap
        update_every: 10
        hostname: 192.168.1.1
        community: public
        options:
          version: 2
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"snmp.conf":"jobs:\n  - name: openwrt_ap\n    update_every: 10\n    hostname: 192.168.1.1\n    community: public\n    options:\n      version: 2\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"netdata-snmp-openwrt","namespace":"netdata"}}
  creationTimestamp: "2026-05-07T05:04:41Z"
  name: netdata-snmp-openwrt
  namespace: netdata
  resourceVersion: "13984324"
  uid: 19a64c28-efe2-422e-b32b-0de5f98a4b85
