apiVersion: v1
data:
  default: |-
    version: v1
    flags:
      migStrategy: none
  icclz1-shared-4: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        renameByDefault: true
        failRequestsGreaterThanOne: true
        resources:
        - name: nvidia.com/gpu
          replicas: 100
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default":"version: v1\nflags:\n  migStrategy: none","icclz1-shared-4":"version: v1\nflags:\n  migStrategy: none\nsharing:\n  timeSlicing:\n    renameByDefault: true\n    failRequestsGreaterThanOne: true\n    resources:\n    - name: nvidia.com/gpu\n      replicas: 4"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"gpu-sharing-config","namespace":"nvidia-device-plugin"}}
  creationTimestamp: "2026-04-25T14:01:26Z"
  name: gpu-sharing-config
  namespace: nvidia-device-plugin
  resourceVersion: "11245941"
  uid: 7af9d2ae-9fc0-4123-b716-aa9d8d1c7adc
