COMPUTED VALUES:
affinity: {}
arguments:
- -f
- /etc/dcgm-exporter/default-counters.csv
basicAuth:
  users: {}
debugDump:
  compression: true
  directory: /tmp/dcgm-exporter-debug
  enabled: false
  retention: 24
extraConfigMapVolumes:
- configMap:
    items:
    - key: metrics
      path: default-counters.csv
    name: exporter-metrics-config-map
  name: exporter-metrics-volume
extraEnv: []
extraHostVolumes: []
extraVolumeMounts:
- mountPath: /etc/dcgm-exporter/default-counters.csv
  name: exporter-metrics-volume
  subPath: default-counters.csv
fullnameOverride: ""
hostPID: false
image:
  pullPolicy: IfNotPresent
  repository: nvcr.io/nvidia/k8s/dcgm-exporter
  tag: 4.5.2-4.8.1-distroless
imagePullSecrets: []
kubeletPath: /var/lib/kubelet/pod-resources
kubernetes:
  enablePodLabels: false
  enablePodUID: false
  podLabelAllowlistRegex: []
  rbac:
    create: true
kubernetesDRA:
  enabled: false
livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 5
nameOverride: ""
namespaceOverride: ""
nodeSelector:
  feature.node.kubernetes.io/pci-10de.present: "true"
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
  initialDelaySeconds: 45
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
rollingUpdate:
  maxSurge: 0
  maxUnavailable: 1
runtimeClassName: ""
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add:
    - SYS_ADMIN
    drop:
    - ALL
  runAsNonRoot: false
  runAsUser: 0
service:
  address: :9400
  annotations: {}
  clusterIP: ""
  enable: true
  internalTrafficPolicy: Cluster
  port: 9400
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
serviceMonitor:
  additionalLabels: {}
  apiVersion: monitoring.coreos.com/v1
  enabled: false
  honorLabels: false
  interval: 15s
  metricRelabelings: []
  relabelings: []
  scrapeTimeout: 10s
tlsServerConfig:
  autoGenerated: true
  ca: ""
  caFilename: ca.crt
  cert: ""
  certFilename: tls.crt
  clientAuthType: ""
  enabled: false
  existingSecret: ""
  key: ""
  keyFilename: tls.key
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
  operator: Exists
