apiVersion: v1
kind: Service
metadata:
  name: netdata-nodeport
  namespace: netdata
  labels:
    app.kubernetes.io/part-of: pre6g-autoscale
    pre6g/component: netdata-nodeport
spec:
  type: NodePort
  selector:
    app: netdata
    release: netdata
    role: parent
  ports:
    - name: http
      protocol: TCP
      port: 19999
      targetPort: 19999
      nodePort: 32163
