apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-victoria-metrics-agent-config
  namespace: monitoring
data:
  scrape.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: vmagent-self
        static_configs:
          - targets:
              - localhost:8429

      - job_name: kube-state-metrics
        static_configs:
          - targets:
              - kube-state-metrics.monitoring.svc:8080

      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            regex: monitoring;node-exporter

      - job_name: kubelet-cadvisor
        kubernetes_sd_configs:
          - role: node
        scheme: https
        metrics_path: /metrics/cadvisor
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            target_label: instance

      - job_name: dcgm-exporter
        scrape_interval: 1s
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - gpu-monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: dcgm-exporter
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9400"
            action: keep
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: kubernetes_node
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod

      - job_name: vllm-serving-pods
        scrape_interval: 1s
        scrape_timeout: 800ms
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ai-serving
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: .*metrics.*
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_init]
            regex: "false"
            action: keep
          - source_labels: [__meta_kubernetes_pod_phase]
            regex: Pending|Running
            action: keep
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: kubernetes_node
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: kubernetes_container

      - job_name: autoscale-api-llamacpp-benchmark
        scrape_interval: 1s
        scrape_timeout: 800ms
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - pre6g-dashboard
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            regex: pre6g-dashboard;autoscale-api
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http
            action: keep
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: kubernetes_node
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod
          - target_label: pre6g_metrics_source
            replacement: autoscale_api
