apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: netdata
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
